FROM php:8-fpm-alpine3.12 as php

RUN apk add --update \
    oniguruma-dev \
    freetype-dev \
    libjpeg-turbo-dev \
    libpng-dev \
		libwebp-dev \
		supervisor \
    libxml2-dev \
    libzip-dev \
    php-xml \
    php-json \
    sqlite \
    m4 \
    gcc make g++ \
    autoconf \
    && docker-php-ext-configure gd --with-freetype=/usr/include/ --with-jpeg=/usr/include/ --with-webp=/usr/include/ \
    && docker-php-ext-install -j$(nproc) gd \
    && docker-php-ext-install pdo_mysql \
    && docker-php-ext-install mbstring \
  	&& docker-php-ext-install exif \
    && pecl install redis \
    && docker-php-ext-enable redis \
    && rm -rf /tmp/pear/download