FROM php:7.2-fpm as php
RUN apt-get update && apt-get install -y \
        libfreetype6-dev \
        libjpeg62-turbo-dev \
        libpng-dev \
    && docker-php-ext-install -j$(nproc) iconv \
    && docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/ \
    && docker-php-ext-install -j$(nproc) gd \
    && docker-php-ext-install pdo_mysql \
	&& pecl install redis-4.3.0 \
	&& docker-php-ext-enable redis

FROM  nginx:stable-alpine as nginx
COPY ./conf/service.conf /etc/nginx/conf.d/default.conf
RUN touch /var/log/nginx/access.log && touch /var/log/nginx/error.log